<#
.SYNOPSIS
Clears all files generated by the Get-OAIFile cmdlet.

.DESCRIPTION
The Clear-OAIFiles function is used to remove all files that were generated by the Get-OAIFile cmdlet. This function does not take any parameters.

.PARAMETER None
This function does not accept any parameters.

.EXAMPLE
Clear-OAIFiles
Removes all files generated by the Get-OAIFile cmdlet.

#>

function Clear-OAIFiles {
    [CmdletBinding()]
    param()
    
    Get-OAIFile | Remove-OAIFile
}
